### ISSUE TITLE
can you support operation mode config for the routes?

### ISSUE THREAD

**Issue by shijl0925** [ShangSky/flask-sugar#5]
I found all routes have operation in the swagger and redoc api docs.
can you support operation mode config for the routes. 

1. 'default': includes all routes in this instance. 

2. 'strict': only includes routes which I wanted.

**Comment by shijl0925** [comment]
for example, If I use the 'flask-security-too' extension, these routes which start with '/auth/' are provided by the extension, but I don't want these operations show in the swagger or redoc UI.


![1E28293D-0C42-4B6C-BA07-9F456A6D9F0D](https://user-images.githubusercontent.com/3942793/151684192-256d0770-3c73-4f52-bd85-22d9b9f5d400.png)

**Comment by ShangSky** [comment]
I just updated flask-sugar to version 0.0.13

you can use [doc_route_filter](https://shangsky.github.io/flask-sugar/doc-route-filter/) to solve your problem

**Comment by shijl0925** [comment]
Get it. Thank you.
