### ISSUE TITLE
Using BaseModel in the GET parameters, is it possible?

### ISSUE THREAD

**Issue by shijl0925** [ShangSky/flask-sugar#6]
I want GET query parameters have some validation. can you support it?

example code:

`
import datetime
from typing import List

from pydantic import Field, BaseModel
from flask_sugar import Query

class SettingQuery(BaseModel):
    page: Optional[int] = Field(..., ge=1, description='page number')
    limit: Optional[int] = Field(..., ge=1, le=25, description='limit number')
    query: str = None

@apis_bp.get("/settings")
def settings(query: SettingQuery = Query(...)):
    return {"query": query.dict()}
`

**Comment by ShangSky** [comment]
I'm not going to support it

**Comment by shijl0925** [comment]
ok, I do the validated job in my code.
