### ISSUE TITLE
[Bug Report] Duplicate swagger/redoc api docs when I use flask_sugar's Blueprint

### ISSUE THREAD

**Issue by shijl0925** [ShangSky/flask-sugar#9]
code: 

```

from flask_sugar import Blueprint
auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.post('/obtain/token', tags=['Auth'])
def obtain_token(payload: ObtainToken):
    ...

```

![20220209102311](https://user-images.githubusercontent.com/3942793/153109898-505a0182-1927-4973-8079-fb09f37edd5c.jpg)

![20220209102349](https://user-images.githubusercontent.com/3942793/153109927-8a4e1dcc-356d-4a57-b4f9-5dec85cd083a.jpg)

**Comment by ShangSky** [comment]
obtain_token will inherit the tag of the auth_bp
You should use like this
```python
from flask_sugar import Blueprint
auth_bp = Blueprint('auth', __name__, url_prefix='/auth', tags=['Auth'])

@auth_bp.post('/obtain/token')
def obtain_token(payload: ObtainToken):
    ...
```

**Comment by shijl0925** [comment]
Thank you, you solve my problem.
